ALTER TABLE "NGUOI_DUNG"
  ADD COLUMN IF NOT EXISTS "avatarUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "avatarPath" TEXT,
  ADD COLUMN IF NOT EXISTS "avatarId" UUID;

CREATE UNIQUE INDEX IF NOT EXISTS "NGUOI_DUNG_avatarId_key"
  ON "NGUOI_DUNG"("avatarId")
  WHERE "avatarId" IS NOT NULL;
