ALTER TABLE "TOUR"
  ADD COLUMN "imageUrl" TEXT,
  ADD COLUMN "galleryImages" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN "itinerary" JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN "commercial" JSONB;

ALTER TABLE "LICH_KHOI_HANH" ADD COLUMN "durationDays" INTEGER;
UPDATE "LICH_KHOI_HANH" AS schedule
SET "durationDays" = tour."durationDays"
FROM "TOUR" AS tour
WHERE schedule."tourId" = tour."id";
ALTER TABLE "LICH_KHOI_HANH" ALTER COLUMN "durationDays" SET NOT NULL;
ALTER TABLE "LICH_KHOI_HANH"
  ADD CONSTRAINT schedule_duration_days CHECK ("durationDays" BETWEEN 1 AND 60);

CREATE TABLE "DANH_GIA_TOUR" (
  "id" UUID NOT NULL,
  "tourId" UUID NOT NULL,
  "userId" UUID NOT NULL,
  "rating" INTEGER NOT NULL,
  "comment" VARCHAR(1200) NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "DANH_GIA_TOUR_pkey" PRIMARY KEY ("id"),
  CONSTRAINT review_rating_range CHECK ("rating" BETWEEN 1 AND 5)
);

CREATE UNIQUE INDEX "DANH_GIA_TOUR_tourId_userId_key"
  ON "DANH_GIA_TOUR"("tourId", "userId");
CREATE INDEX "DANH_GIA_TOUR_tourId_createdAt_idx"
  ON "DANH_GIA_TOUR"("tourId", "createdAt");
CREATE INDEX "DANH_GIA_TOUR_userId_createdAt_idx"
  ON "DANH_GIA_TOUR"("userId", "createdAt");

ALTER TABLE "DANH_GIA_TOUR"
  ADD CONSTRAINT "DANH_GIA_TOUR_tourId_fkey"
  FOREIGN KEY ("tourId") REFERENCES "TOUR"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DANH_GIA_TOUR"
  ADD CONSTRAINT "DANH_GIA_TOUR_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "NGUOI_DUNG"("id") ON DELETE CASCADE ON UPDATE CASCADE;
