CREATE TABLE "PASSWORD_RESET_CHALLENGE" (
  "id" UUID NOT NULL,
  "userId" UUID NOT NULL,
  "codeHash" TEXT NOT NULL,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  "consumedAt" TIMESTAMPTZ(3),
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PASSWORD_RESET_CHALLENGE_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "PASSWORD_RESET_CHALLENGE_userId_createdAt_idx"
ON "PASSWORD_RESET_CHALLENGE"("userId", "createdAt");

CREATE INDEX "PASSWORD_RESET_CHALLENGE_expiresAt_idx"
ON "PASSWORD_RESET_CHALLENGE"("expiresAt");

ALTER TABLE "PASSWORD_RESET_CHALLENGE"
ADD CONSTRAINT "PASSWORD_RESET_CHALLENGE_userId_fkey"
FOREIGN KEY ("userId") REFERENCES "NGUOI_DUNG"("id")
ON DELETE CASCADE ON UPDATE CASCADE;
